"""Add character_hat relationship

Revision ID: 046e2cf53aab
Revises: 61502e350b31
Create Date: 2021-01-19 23:06:05.157167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '046e2cf53aab'
down_revision = '61502e350b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('hat_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'characters', 'clothes', ['hat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'hat_id')
    # ### end Alembic commands ###
