"""Add clothes table

Revision ID: 61502e350b31
Revises: 96ddf42db8f4
Create Date: 2020-12-15 20:58:24.886551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61502e350b31'
down_revision = '96ddf42db8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('article', sa.Enum('hat', name='article'), nullable=True),
    sa.Column('color', sa.Enum('green', 'purple', 'yellow', name='color'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothes')
    # ### end Alembic commands ###
